// 200+ Vehicle Inspection Points organized by category
export interface InspectionPointDef {
  name: string;
  category: string;
  input_type: "dropdown" | "slider" | "radio" | "text" | "photo";
  deduction_major: number;
  deduction_minor: number;
  options?: string[];
}

export const INSPECTION_POINTS: InspectionPointDef[] = [
  // ============ EXTERIOR (45 points) ============
  {
    name: "Front Bumper Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Bumper Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Bonnet/Hood Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Trunk/Boot Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Roof Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Left Front Fender",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Left Rear Fender",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Right Front Fender",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Right Rear Fender",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Left Front Door",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Left Rear Door",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Right Front Door",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Right Rear Door",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Windshield Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Windshield",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Left Side Mirror",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Right Side Mirror",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Left Headlight",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Right Headlight",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Left Tail Light",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Right Tail Light",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Fog Lights",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "DRL (Daytime Running Lights)",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Front Grille",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Wheel Arches",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Door Handles",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Antenna",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Wiper Blades",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Rear Wiper",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Sunroof/Moonroof",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Paint Overall Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Paint Thickness Uniformity",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rust/Corrosion",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Body Panel Gaps",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Window Tinting",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Door Seals/Rubber",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Chrome/Trim Pieces",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "License Plate Light",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Fuel Cap",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Rear Spoiler",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Mud Flaps",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Side Skirts",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Exhaust Tip Condition",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Badge/Emblems",
    category: "Exterior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Exterior Notes",
    category: "Exterior",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },

  // ============ INTERIOR (40 points) ============
  {
    name: "Dashboard Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Steering Wheel Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Steering Wheel Controls",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Driver Seat Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Passenger Seat Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Seats Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Seat Belts",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Seat Adjustment (Electric)",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Seat Adjustment (Manual)",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Center Console",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Gear Knob/Shifter",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Handbrake/Parking Brake",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Floor Mats",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Carpet Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Headliner/Roof Lining",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Sun Visors",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Vanity Mirrors",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Interior Lights",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Glove Box",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Cup Holders",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Door Panels",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Door Lock Mechanism",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Window Controls",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Power Windows (All)",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Rear View Mirror",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Trunk/Boot Interior",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Spare Tire",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Jack & Tools",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Interior Smell",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Cigarette Burns/Stains",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Door Hinges",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Boot/Trunk Lock",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Key/Remote Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Second Key Availability",
    category: "Interior",
    input_type: "radio",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Owner Manual",
    category: "Interior",
    input_type: "radio",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Interior Trim Pieces",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Pedals Condition",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Horn",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Cigarette Lighter/12V Port",
    category: "Interior",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Interior Notes",
    category: "Interior",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },

  // ============ ENGINE (35 points) ============
  {
    name: "Engine Start",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 1.0,
    deduction_minor: 0.3,
  },
  {
    name: "Engine Idle",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Engine Sound",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Engine Vibration",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Engine Oil Level",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Engine Oil Condition",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Oil Leaks",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Coolant Level",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Coolant Condition",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Coolant Leaks",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Radiator Condition",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Radiator Fan",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Drive Belts",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Timing Belt/Chain",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Battery Condition",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Battery Terminals",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Air Filter",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Spark Plugs",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Transmission Fluid",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Transmission Performance",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 1.5,
    deduction_minor: 0.5,
  },
  {
    name: "Clutch (if Manual)",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Gear Shifting",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Acceleration Response",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Engine Temperature",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Exhaust Smoke",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Exhaust Sound",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Power Steering Fluid",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Brake Fluid Level",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Washer Fluid",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Engine Bay Cleanliness",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Hoses & Connections",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Engine Mounts",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Turbo/Supercharger (if equipped)",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Catalytic Converter",
    category: "Engine",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Engine Notes",
    category: "Engine",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },

  // ============ SUSPENSION (25 points) ============
  {
    name: "Front Left Shock Absorber",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Front Right Shock Absorber",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Left Shock Absorber",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Right Shock Absorber",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Front Suspension Noise",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Suspension Noise",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Steering Play",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Steering Response",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Power Steering Operation",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Wheel Alignment",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Wheel Balancing",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Ball Joints",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Tie Rod Ends",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Control Arms",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Sway Bar Links",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "CV Joints/Boots",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Strut Mounts",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Springs Condition",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Ride Height",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Ride Comfort",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Road Noise",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Wheel Bearings",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Driveshaft",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "4WD/AWD System (if equipped)",
    category: "Suspension",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Suspension Notes",
    category: "Suspension",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },

  // ============ ELECTRONICS (35 points) ============
  {
    name: "Infotainment System",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Touchscreen Display",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Audio System/Speakers",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Bluetooth Connectivity",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "USB/AUX Ports",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Navigation System",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Backup/Reverse Camera",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Parking Sensors",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "AC Cooling Performance",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "AC Heating Performance",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "AC Blower All Speeds",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Rear AC/Vents",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Climate Control",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Instrument Cluster",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Speedometer",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Tachometer",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Fuel Gauge",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Temperature Gauge",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Odometer Reading",
    category: "Electronics",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },
  {
    name: "Warning Lights (Check Engine)",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 1.0,
    deduction_minor: 0.3,
  },
  {
    name: "Warning Lights (ABS)",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Warning Lights (Airbag)",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Warning Lights (Other)",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Central Locking",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Keyless Entry",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Push Start",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Cruise Control",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Heated Seats",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Seat Memory",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Auto-dimming Mirror",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Rain Sensor",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Light Sensor",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Immobilizer",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Electrical Wiring",
    category: "Electronics",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Electronics Notes",
    category: "Electronics",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },

  // ============ UNDERBODY (20 points) ============
  {
    name: "Underbody Rust",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Underbody Damage",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Frame/Chassis Condition",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 1.0,
    deduction_minor: 0.3,
  },
  {
    name: "Sub-Frame",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Oil Pan",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Transmission Pan",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Exhaust System",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Muffler Condition",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Fuel Lines",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Brake Lines",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Undercoating",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Splash Guards",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Heat Shields",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Differential (if applicable)",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Transfer Case (if 4WD)",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Floor Pan Condition",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Accident Repair Evidence",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 1.0,
    deduction_minor: 0.3,
  },
  {
    name: "Welding Marks",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Fluid Leaks Under Vehicle",
    category: "Underbody",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Underbody Notes",
    category: "Underbody",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },

  // ============ TYRES & BRAKES (25 points) ============
  {
    name: "Front Left Tyre Brand/Size",
    category: "Tyres & Brakes",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },
  {
    name: "Front Left Tyre Tread Depth",
    category: "Tyres & Brakes",
    input_type: "slider",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Front Left Tyre Condition",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Front Right Tyre Brand/Size",
    category: "Tyres & Brakes",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },
  {
    name: "Front Right Tyre Tread Depth",
    category: "Tyres & Brakes",
    input_type: "slider",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Front Right Tyre Condition",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Left Tyre Brand/Size",
    category: "Tyres & Brakes",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },
  {
    name: "Rear Left Tyre Tread Depth",
    category: "Tyres & Brakes",
    input_type: "slider",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Left Tyre Condition",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Right Tyre Brand/Size",
    category: "Tyres & Brakes",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },
  {
    name: "Rear Right Tyre Tread Depth",
    category: "Tyres & Brakes",
    input_type: "slider",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Right Tyre Condition",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Spare Tyre Condition",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.15,
    deduction_minor: 0.05,
  },
  {
    name: "Alloy Wheels Condition",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "Wheel Covers/Hubcaps",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.05,
    deduction_minor: 0.02,
  },
  {
    name: "Wheel Nuts/Bolts",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.1,
    deduction_minor: 0.05,
  },
  {
    name: "Front Brake Pads",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Rear Brake Pads",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Brake Discs/Rotors (Front)",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Brake Discs/Rotors (Rear)",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Brake Performance",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Brake Noise",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.2,
    deduction_minor: 0.1,
  },
  {
    name: "ABS System",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.5,
    deduction_minor: 0.2,
  },
  {
    name: "Parking Brake Effectiveness",
    category: "Tyres & Brakes",
    input_type: "dropdown",
    deduction_major: 0.3,
    deduction_minor: 0.1,
  },
  {
    name: "Tyres & Brakes Notes",
    category: "Tyres & Brakes",
    input_type: "text",
    deduction_major: 0,
    deduction_minor: 0,
  },
];
